name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Linux
      run: cargo build --release
    - name: Upload Linux binary
      uses: actions/upload-artifact@v2
      with:
        name: tunnelvision-server
        path: target/release/manylinux/tunnelvision-server
    - name: Download source
      run: git clone https://github.com/sluijs/tunnelvision.git
      with:
        ref: main
        token: ${{ secrets.PAT }}
    - name: Copy Linux binary
      run: |
        cp target/release/manylinux/tunnelvision-server tunnelvision/tunnelvision/bin/
    - name: Build Linux wheel
      run: |
        cd tunnelvision
        python setup.py bdist_wheel --plat-name manylinux2014_x86_64
      shell: bash
    - name: Upload Linux wheel
      uses: actions/upload-artifact@v2
      with:
        name: tunnelvision-0.3.2-py3-none-manylinux1_x86_64.whl
        path: tunnelvision/dist/*.whl
